### ISSUE TITLE
MI:0524 tem edit

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#357]
At the moment MI:0524 term is defined as:

Name: calmodulin binding peptide plus protein a tag
Definition: Tag encoding a calmodulin binding peptide, a TEV cleavage site, and the Staphylococcus aureus Protein A fused to a target protein and the introduction of the construct into the host cell or organism, maintaining the expression of the fusion protein at, or close to, its natural level. The fusion protein and associated components are recovered from cell extracts by affinity selection on an IgG matrix. After washing, the TEV protease is added to release the bound material. The eluate is incubated with calmodulin-coated beads in the presence of calcium. This second affinity step is required to remove the TEV protease as well as traces of contaminants remaining after the first affinity selection. After washing, the bound material is released with EGTA. This tag allows two steps purification steps ensuring a highly selective purification of the tapped protein (first round of selection on the protein A, a high affinity tag) under mild condition (non denaturant pH or conditions required to remove the tag).

I'd think that the commonly used name of this tag seems to be just 'TAP tag'. Detailed description of the purification procedure seems to be out of place - what if someone uses the tag in some different way ? Is it then still a TAP tag 
or something else ?  

Can we please shorten the name and definition of this term to read: 

Name: TAP tag.
Definition: Tag encoding a calmodulin binding peptide, a TEV cleavage site, and the Staphylococcus aureus Protein A fused to a target protein. The tag allows two purification steps ensuring a highly selective purification of the tagged protein under close to native conditions.

lukasz

Reported by: lukasz99

**Comment by pporrasebi** [comment]
This was dealt with already, please close the issue.
