### ISSUE TITLE
insertion mutation

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#361]
Puissant et al (2014) (24525236)

I have had to add as a Feature - region - a "ITD" - Internal Tandem duplication mutation- as there appears to be no better way to add an insertion of >1/2 amino acids...it could be added as a Fusion protein, but in this instance this would not be correct either...

Reported by: qweqwe6

**Comment by pporrasebi** [comment]
This can be dealt with using current model using the following format: arg_ala123-124arg_ala_arg_ala [Original sequence: RA, resulting sequence: RARA].

No further action taken.

**Comment by noedelta** [comment]
Can be closed?
