### ISSUE TITLE
New URL fro matrixdb

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#384]
_From @noedelta on July 25, 2016 10:18_

Matrix DB has a new domain matrixdb.univ-lyon1.fr, and the URL needs to be updated to have the proper link in our applications.

Example:
http://matrixdb.univ-lyon1.fr/cgi-bin/current/newPort?type=biomolecule&value=MULT_1_human

[Term]
id: MI:0917
name: matrixdb
def: "Knowledgebase of the extracellular matrix storing experimentally determined interactions involving extracellular biomolecules. It includes protein-protein, protein-polysaccharide, and protein-lipid interactions." [PMID:19147664]
subset: PSI-MI_slim
**OLD->**xref: search-url: "http://matrixdb.ibcp.fr/cgi-bin/current/newPort?type=biomolecule&value=${ac}"
**NEW->**xref: search-url: "http://matrixdb.univ-lyon1.fr/cgi-bin/current/newPort?type=biomolecule&value=${ac}"
is_a: MI:0461 ! interaction database
is_a: MI:0973 ! imex source

_Copied from original issue: MICommunity/psidev#605_

**Comment by bmeldal** [comment]
The above issue is done but they now have moved to https. I updated the Editor but it needs changing in the ontology file.
