### ISSUE TITLE
New MI term for DAP-seq interactions?

### ISSUE THREAD

**Issue by nprovart** [HUPO-PSI/psi-mi-CV#391]
Would it be possible to request a new MI: detection method ID for "DNA Affinity Purification-sequencing" (DAP-seq, as per this paper:  doi: 10.1016/j.cell.2016.04.038. It is similar to Chip-seq). We've got ~2.8 million of these protein-DNA interactions in our PSICQUIC-enabled DB without any MI term for them! 

Thanks,

Nick
.........................................
Nicholas Provart, PhD
Professor, Plant Cyberinfrastructure & Systems Biology
Member: CAGEF, IAIC, ISCB, CSPB

Department of Cell & Systems Biology, University of Toronto
25 Willcocks St., Rm. 3072, Toronto, ON. M5S 3B2. CANADA
Phone. +1-416-978-7141, Skype. nicholas.provart, Fax. +1-425-675-7036
URL. http://csb.utoronto.ca/faculty/nicholas-provart
The Bio-Analytic Resource. http://www.BAR.utoronto.ca   
email. nicholas.provart@utoronto.ca

**Comment by pporrasebi** [comment]
New terms have been created. Apologies for the delay.
