### ISSUE TITLE
NTR: photon donor/acceptor in experimental roles

### ISSUE THREAD

**Issue by liviap** [HUPO-PSI/psi-mi-CV#394]
New 'experimental role' terms requested:

luminescence/photon donor
luminescence/photon acceptor 

for BRET pairs.

Livia

**Comment by pporrasebi** [comment]
Hi All

Sorry to be annoying when I am sure many of you are engrossed in 
something or another at Biocuration, but I have just noticed something 
somewhat belatedly...

I have been annotating several interactions with Int.Det Method = BRET.

According to the PSI-MI Google document "Exp Role" should be "PHOTON 
donor/acceptor".

I have looked at the public web site and after looking at ~5-6 pages 
under "Advanced Search" for BRET,  have not been able to find even a 
SINGLE entry for PHOTON donor/acceptor.
Mostly they are all "Fluorescence Donor/Acceptors" + a few 
"funnies/unusual" entries, for Exp.Role.


However when searching for "pbiorole:photon" I found only ONE entry with 
BRET as the Interaction Det. Method (- in pmid:23105096 !!) The other 
(few) entries are for  Interaction Det.Method = "Phosphotransferase 
Assay", which is probably not the appropriate term to have used.

A couple of points:- although the PSI-MI table only says "EXP. Role" 
there is no column for "Biological Role" - which is the only place where 
"PHOTON donor/acceptor"  can be found.


So should all the BRET interactions be re-entered with the  correct 
Biological Role (and presumably Exp. role as "unspecified", or do we 
leave well alone?

The term "fluorescence Acceptor" might be OK here,  but as the donor is 
producing light by luminesence, not fluorescence...

yours

Mgt
_______________________________________________
Intact-curators mailing list
Intact-curators@ebi.ac.uk
https://listserver.ebi.ac.uk/mailman/listinfo/intact-curators
