### ISSUE TITLE
Definition of gene could be more precise

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#402]
Currently the definition of gene is:

interactor for genetic interaction.

However I think it does not reflect the use the term in the current curation standards.

**Comment by pporrasebi** [comment]
Replaced with an adaptation of the definition of gene as given by the sequence ontology (http://www.sequenceontology.org/browser/current_release/term/SO:0000704): 

"A genomic region (or regions) that includes all of the sequence elements necessary to encode a functional transcript. A gene may include regulatory regions, transcribed regions and/or other functional sequence regions."
