### ISSUE TITLE
Electron imaging terms need update...

### ISSUE THREAD

**Issue by lukasz99** [HUPO-PSI/psi-mi-CV#403]
1) 'electron tomography' should be moved to be a child of transmission em and renamed
'3D  electron microscopy' (3D-EM as as short name/label)  with definition that reads:
Three-dimensional (3D) reconstruction of single, transparent objects from acollection of projection images recorded with a transmission electron microscope. It offers the opportunity to obtain 3D information on structural cellular arrangements with a high resolution.
 
 - this will create no problems as it is generic enough to cover practically all  3D EM structures so the term will remain correct for already curated records

2) 3D-EM can be split into 
 a)  'Single particle electron microscopy 3D reconstruction' (3D-EM-single as label) defined as:

Three-dimensional (3D) reconstruction of single, transparent objects from a collection of images of randomly oriented particles recorded with a transmission electron microscope. 

- this covers the most common 'cryoEM' and can be used retroactively for all structures *with defined stoichiometry* currently annotated as 'electron tomography' 
 
b)  'Electron microscopy 3D helical reconstruction (3D-EM-helical) with definition:

 Three-dimensional (3D) reconstruction of helical objects from a collection of fiber images recorded with a transmission electron microscope. 

- this covers helical reconstruction of fibers of various sorts (actin, myosin, microtubules, amyloids , etc) and can be retroactively applied to structures annotated with 'electron tomography'  *with no stoichiometry info*

c) Electron tomography (3D-EM-tomo note: this is *new* term) with definition

Three-dimensional (3D) reconstruction of single, transparent objects from a series of projection images from a tilt series recorded with a transmission electron microscope.
 
- I don't recollect curating any interactions like this (these would be mostly bacterial secretion complexes) so there won't be, most likely, any 'legacy' uses.

Please, note, that, in principle all the above can be performed in low temp (aka 'cryo') and
with/without staining - the structure determination terms should left generic enough to cover all the variants, otherwise we will end up with a pile of very specific terms with limited use (so, please, no 'cryoEM').  if one cares about cryo/staining (personally  I don't) these should be entered as sample preparation/experimental conditions as this is what they actually are.

**Comment by pporrasebi** [comment]
I have incorporated the new electron tomography term and moved the old one to '3D electron microscopy'. 

I am not really convinced about the need for the 3D-EM split, to be honest. Are the methods really that different that we need the helical/single molecule distinction? Also, could there be non-helical, polymeric structures where stoichiometry is not known? In those cases the single molecule term would not be appliable, but neither the helical term. Would you be OK without the split single molecule/helical terms?

**Comment by lukasz99** [comment]
On 7/17/19 6:36 AM, Pablo Porras wrote:
> I have incorporated the new electron tomography term and moved the old one to '3D electron microscopy'.
> 
> I am not really convinced about the need for the 3D-EM split, to be honest. 
>Are the methods really that different that we need the helical/single molecule
>distinction? 

yes, they are - if a fiber does not twist (and there such thingies
do exist) helical reconstruction does not work because all the segments
within one fiber are oriented the same way. coincidentally, single
particle reconstruction also tends to fail as untwisted fibers like
to orient themselves the same way when landing on the EM grid which
results in just one orientation showing up over and over again.
In general, to get 3D shape of an object it must be observed from many
directions - the three ways to get multiple orientations is to:

   - control orientation of the object. It works for any type of object.
            -> tomography

   - let the object orient itself in a random fashion (or as close a possible
     to random). It works for any type of object (provided it behaves well;
     fibers don't - they somehow end up parallel to em grind)
            -> single particle reconstruction

   - split the object into segments, each rotated a little bit
     more than the previous one (this works only for twisted fibers)
            -> helical reconstruction

these correspond to the three cv terms. it's all (and only) about
how the orientation is controlled. note, that stiochiometry does not
get into the definitions - it's just a diagnostic which tells one
which method might (or will not) work in a specific case.

>Also, could there be non-helical, polymeric structures where >stoichiometry is not known?

yup. untwisted fibers.

>In those cases the single molecule term would >not be appliable,

it would. such cases got to be handled as single particles.
however, single particle reconstruction does not work b/c such
fibers tend to orient themselves the same way over and over and over
again. very annoying !!!

but neither the helical term. Would you be OK without
>the split single molecule/helical terms?

not really - these are different methods. I've been recently surrounded
by a herd of people doing this - there's a spanking new cryo-EM running
in the room just below my office. I'm just regurgitating what the people
playing with the toy tend to say...

lukasz

-- 
-------------------------------------------------------------------------
  Lukasz Salwinski                             PHONE:        310-825-1402
  UCLA-DOE Institute                             FAX:        310-206-3914
  UCLA, Los Angeles                            EMAIL: lukasz@mbi.ucla.edu
-------------------------------------------------------------------------

**Comment by pporrasebi** [comment]
OK, sounds reasonable. I will create the terms and close the tickets shortly.
