### ISSUE TITLE
New xref term: complex fragment

### ISSUE THREAD

**Issue by lukasz99** [HUPO-PSI/psi-mi-CV#405]
Hello,
  a relatively recent cryo-EM technique called focused refinement  (see, eg PMID: 29856314, https://elifesciences.org/articles/36861) results in structures reported as collections of PDB files - one (or more) of them models entire  complex but a number of additional ones correspond to individually refined (but otherwise *not autonomous*) subfragments. All of these should be entered as cross-references but 'identity'  as cross-reference type does not seem particularly appropriate - the structures do not exist on their own but correspond to fragments of bigger structures.  
So what about adding a new 'complex fragment' cross-reference type to use in such cases ?   
it would be used for pdbs  that do not correspond to complete complexes.

**Comment by lukasz99** [comment]
On 10/28/19 9:58 AM, Pablo Porras wrote:
> We have 'subset' (MI:2179, synonym 'part of'), defined as '_Reference to the corresponding object in another database. It implies the object is part of a cross-referenced entity (usually a complex)._'
> 
> Would this do? I would say it fits.
> 

which way does it go ?  is the referenced object 'part of' the one
that the xref is hanging off or does it go the other way ?
is the pdb part of the interaction or is the interaction part of pdb ?

lukasz


-- 
-------------------------------------------------------------------------
  Lukasz Salwinski                             PHONE:        310-825-1402
  UCLA-DOE Institute                             FAX:        310-206-3914
  UCLA, Los Angeles                            EMAIL: lukasz@mbi.ucla.edu
-------------------------------------------------------------------------

**Comment by pporrasebi** [comment]
The pdb is part of the interaction: the xref would hang on an interaction/complex and refer to a PDB entry that represents part of it. We have been using it on the Complex Portal, here's an example: https://www.ebi.ac.uk/complexportal/complex/CPX-152. Go to the structures section and click through the different structures to see how they only represent part of the complex.

**Comment by lukasz99** [comment]
On 10/28/19 10:31 AM, Pablo Porras wrote:
> The pdb is part of the interaction: the xref would hang on an interaction/complex and refer to a PDB entry that represents part of it. We have been using it on the Complex Portal, here's an example: https://www.ebi.ac.uk/complexportal/complex/CPX-152. Go to the structures section and click through the different structures to see how they only represent part of the complex.
> 

so, I'd guess. then it's ok.
lukasz


-- 
-------------------------------------------------------------------------
  Lukasz Salwinski                             PHONE:        310-825-1402
  UCLA-DOE Institute                             FAX:        310-206-3914
  UCLA, Los Angeles                            EMAIL: lukasz@mbi.ucla.edu
-------------------------------------------------------------------------

**Comment by pporrasebi** [comment]
OK, closing the issue, then.
