### ISSUE TITLE
Inferred-from cross-reference type (MI:1351) definition too specific ?

### ISSUE THREAD

**Issue by lukasz99** [HUPO-PSI/psi-mi-CV#408]
Current definition:
 >Refers to the original experimentally verified object from which a modelled curated complex has been derived.

seems to be too specific - there's much more than just modelled curated complexes that can be inferred (eg binary interactions from associations). Can the definition refer to the 'parent object' or 'described object' :

  >Refers to the original experimentally verified object from which the parent object has been derived.

or

 >Refers to the original experimentally verified object from which the described object has been derived.

**Comment by pporrasebi** [comment]
Sounds fine. Apparently this term was created to reference complexes inffered by homology from a different species. I will amend the definition with the second of the two options you suggested: 

Refers to the original experimentally verified object from which the described object has been derived.

**Comment by lukasz99** [comment]
On 8/7/19 11:55 PM, Pablo Porras wrote:
> Sounds fine. Apparently this term was created to reference complexes inffered by homology from a different species. I will amend the definition with the second of the two options you suggested:
> 
> Refers to the original experimentally verified object from which the described object has been derived.

thanks
lukasz


-- 
-------------------------------------------------------------------------
  Lukasz Salwinski                             PHONE:        310-825-1402
  UCLA-DOE Institute                             FAX:        310-206-3914
  UCLA, Los Angeles                            EMAIL: lukasz@mbi.ucla.edu
-------------------------------------------------------------------------
