### ISSUE TITLE
misplaced ECO and psi-mi ontology references

### ISSUE THREAD

**Issue by lukasz99** [HUPO-PSI/psi-mi-CV#410]
ECO term  (MI:1331)is described as :

>The Evidence Ontology (ECO) describes types of scientific evidence
>within the realm of biological research that can arise from laboratory
>experiments, computational methods, manual literature curation, and
>other means.

Interaction database branch (MI:0461)is described as:

>Databases that contain experimental or predictive molecular interaction
>data.

These two do not get together no matter how hard I try :o/  The same
actually applies to psi-mi self-reference term (MI:0488) - both are
describing ontologies, not interaction databases. Can they be moved out
of interaction database branch either one level up to 'database' (then
each is pretending to be a 'database' of terms, which seems to be 
somewhat ok) or to a new, more specific, 'controlled vocabulary' term
within 'database' (MI:0444) with a definition that states, more or less,

>A collection of words and phrases, which are used to tag units of 
>information (e.g. database records or their parts) so that they may be 
>more easily retrieved by a search.

**Comment by pporrasebi** [comment]
The whole database branch needs thorough revision, I fully agree with this issue. I will devote some more time to revise the current classification and shuffle terms around and come back to you about this.

**Comment by pporrasebi** [comment]
Both ECO and EDAM have been moved from being children of 'interaction database' to 'experiment database', which much more accurately describes the type of resources they really are.

**Comment by lukasz99** [comment]
On 11/19/19 8:43 AM, Pablo Porras wrote:
> Both ECO and EDAM have been moved from being children of 'interaction database' to 'experiment database', which much more accurately describes the type of resources they really are.
> 

looks better :o)
thanks
lukasz

-- 
-------------------------------------------------------------------------
  Lukasz Salwinski                             PHONE:        310-825-1402
  UCLA-DOE Institute                             FAX:        310-206-3914
  UCLA, Los Angeles                            EMAIL: lukasz@mbi.ucla.edu
-------------------------------------------------------------------------
