### ISSUE TITLE
Unique short label curated by PSI-MI are not unique

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#413]
This to terms share the same label:

MI:0445
https://www.ebi.ac.uk/ols/search?q=MI%3A0445&groupField=iri&exact=on&start=0&ontology=mi

MI:1336
https://www.ebi.ac.uk/ols/search?q=MI%3A1336&groupField=iri&exact=on&start=0&ontology=mi

**Comment by pporrasebi** [comment]
MI:0445 label has been amended to 'literature xref'.
