### ISSUE TITLE
"Chromosome conformation capture assay" is not a type of chromatin immunoprecipitation (or any affinity techonlogy)

### ISSUE THREAD

**Issue by chris-grove** [HUPO-PSI/psi-mi-CV#419]
Hello,

I just wanted to point out that the assay "chromosome conformation capture assay" (MI:1218)

https://www.ebi.ac.uk/ols/ontologies/mi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMI_1218

is not, actually, a type of chromatin immunoprecipitation assay, or any affinity techonology for that matter. I suppose the best alternative parent term would be "cross-linking study":

https://www.ebi.ac.uk/ols/ontologies/mi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMI_0030

Thanks!

**Comment by pporrasebi** [comment]
Agreed, the term will be moved as child of cross-linking study and its short label corrected to avoid any association with chip.
