### ISSUE TITLE
Duplicate genetic interaction type terms/nodes for "opposing epistasis"

### ISSUE THREAD

**Issue by chris-grove** [HUPO-PSI/psi-mi-CV#421]
I found that "opposing epistasis" has two duplicate nodes in the ontology/CV:

opposing epistasis:
http://purl.obolibrary.org/obo/MI_1276
http://purl.obolibrary.org/obo/MI_1285

I think MI_1285 should be merged into MI_1276

**Comment by pporrasebi** [comment]
Terms merged into MI:1276.
