### ISSUE TITLE
NTR: CV for kcat/km as parameter

### ISSUE THREAD

**Issue by kalpanaps** [HUPO-PSI/psi-mi-CV#424]
kcat/km reflects both binding and catalytic events – indicates how the velocity varies according to
how often the enzyme and substrate combine.

**Comment by pporrasebi** [comment]
New term name: kcat/km
Synonyms: specificity constant, catalytic efficiency
Proposed definition: This parameter represents the rate of the reaction at negligible substrate concentration, indicating how the velocity varies according to how often enzyme and substrate combine.

**Comment by pporrasebi** [comment]
New term MI code: MI:2357

**Comment by kalpanaps** [comment]
Thank you Pablo!
-----------------------------------------------------

Kalpana Panneerselvam

IntAct-Scientific Database Curator
European Molecular Biology Laboratory
European Bioinformatics Institute (EMBL-EBI)
Wellcome Genome Campus
Hinxton
Cambridge CB10 1SD
United Kingdom
Tel:   +44 1223 494 468
email:  kalpanap@ebi.ac.uk
