### ISSUE TITLE
NEW interaction database: miRBase

### ISSUE THREAD

**Issue by bmeldal** [HUPO-PSI/psi-mi-CV#426]
Name: miRBase
synonym: mirbase

Description:
A searchable database of published miRNA sequences and annotation. Each entry in the miRBase Sequence database represents a predicted hairpin portion of a miRNA transcript (termed mir in the database), with information on the location and sequence of the mature miRNA sequence (termed miR). Both hairpin and mature sequences are available for searching and browsing, and entries can also be retrieved by name, keyword, references and annotation. All sequence and annotation data are also available for download.

Existing database entry: EBI-11169752, IA:2967

Homepage: http://www.mirbase.org/

Search url (please double check!): http://www.mirbase.org/cgi-bin/mirna_entry.pl?acc={}

Original creator: Nancy Campbell

**Comment by pporrasebi** [comment]
Created and amended in IntAct internal database.
