### ISSUE TITLE
NEW Tag: GBG ( Gag‐β‐gal) Tag

### ISSUE THREAD

**Issue by lukasz99** [HUPO-PSI/psi-mi-CV#427]
The tag came originally from PMID: 10459153 and was used in  PMID:20154085. It is based on
 HIV‐1 Gag‐β‐galactosidase so, I'd guess, it would be enzyme tag.

**Comment by pporrasebi** [comment]
Would a generic beta-galactosidase tag do or do we need the more specific HIV one? Just so we can use it for similar tags.

**Comment by lukasz99** [comment]
On 6/30/20 10:18 AM, Pablo Porras wrote:
> Would a generic beta-galactosidase tag do or do we need the more specific HIV one? Just so we can use it for similar tags.
> 

generic would be fine, I'd guess.

lukasz

-- 
------------------------------------------------------------------------
   Lukasz Salwinski                            PHONE:        310-825-1402
   UCLA-DOE Institute                            FAX:        310-206-3914
   UCLA, Los Angeles                           EMAIL: lukasz@mbi.ucla.edu
----------------------------------------------------------------------H-

**Comment by pporrasebi** [comment]
Done.
