### ISSUE TITLE
New method: Split Intein-Mediated Protein Ligation

### ISSUE THREAD

**Issue by sandraorchard** [HUPO-PSI/psi-mi-CV#432]
PMID: 32415080 (Big Igor) 

Synonym - SIMPL

Def: Bait protein is fused to a standard protein fusion tag and an intein  fragment,  prey a with a different protein fusion tag and the complementary intein fragment. The bait and prey are co-expressed in a cell line where the association of bait and prey brings the intein fragments into close proximity, allowing them to reconstitute a fully functional intein, which then catalyzes its own excision and the concurrent ligation of the bait and the prey peptides (as well as the standard protein fusion tags). The resulting spliced protein can be resolved by regular western blot analysis due to its altered mobility, while the presence of the standard protein fusion tags allows visualization or purification of protein using regular biochemical techniques.

Will also require the intein fragment tags.

**Comment by sandraorchard** [comment]
I think this will be a rather weird looking PCA with western blot as a readout. There is also an ELISA method used for higher throughput - I think the existing ELISA plus tags will be OK for this but you may want to add it as a separate method as the intein splicing will have happened first.

**Comment by pporrasebi** [comment]
New terms created (MI:2362,MI:2362,MI:2363), should be up on OLS in a few hours.
