### ISSUE TITLE
Some xrefs should be relationships

### ISSUE THREAD

**Issue by cthoyt** [HUPO-PSI/psi-mi-CV#434]
Many terms seem to be annotating their types using formations like this:
```
[Term]
id: MS:1000005
name: sample volume
def: "Total volume of solution used." [PSI:MS]
xref: value-type:xsd\:float "The allowed value-type for this CV term."
is_a: MS:1000548 ! sample attribute
relationship: has_units UO:0000098 ! milliliter
```

This isn't typically how xrefs are used. I think it would be better to create a new `[Typedef]` for `value-type` that would allow a relationship like

`relationship: MS:value_type xsd:float`

**Comment by cthoyt** [comment]
I'm not exactly sure how this OBO document is created/edited since there aren't any contribution guidelines. I'd be willing to make a PR that would demonstrate this if it's okay to edit the OBO file directly

**Comment by pporrasebi** [comment]
Hi,

Thanks for the feedback. We have been defining xrefs in the way you indicate to support existing infrastructure. I realize this is not fully correct, but the change would most probably have knockdown effects on several of the tools and websites usign this CV. That said, I believe we should study the implications of the change and the potential benefits of having the OBO file properly formatted, so I would be fine with you creating your own branch and illustrating how the changes would work, if that's feasible. Then we can test in exisiting tools and see what would be its impact.

**Comment by cthoyt** [comment]
Hi @pporrasebi I'm sorry but it appears I've put this issue in the wrong PSI controlled vocabulary. This was actually an issue in PSI-MS. I've made a PR there (https://github.com/HUPO-PSI/psi-ms-CV/pull/50) to demonstrate. Would you like me to close this issue and open another one there? It seems there are quite a few more contributors there that might have opinions

**Comment by pporrasebi** [comment]
OK, I will close this issue here, discussion continues at https://github.com/HUPO-PSI/psi-ms-CV/pull/50.
