### ISSUE TITLE
Align PSI-MI with the Relations Ontology and BFO

### ISSUE THREAD

**Issue by cthoyt** [HUPO-PSI/psi-mi-CV#436]
PSI-MI makes four custom `[Typedef]` entries at the bottom of its OBO file. Three of these could be aligned with the standard Basic Formal Ontology (BFO) and Relation Ontology (RO).

| PSI-MI | External ID | External Name |
|---------|--------|--------|
| contains | BFO:0000051 | has part |
| part_of | BFO:0000050 | part of |
| derives_from | RO:0001000 | derives from |
| has_functional_parent | - | - |

The last, `has_functional_parent` also has an analogous typedef in ChEBI, but seems like something that would best be encoded in RO such that it could be standardized across multiple ontologies (cc: @cmungall, @matentzn, @amalik01)

**Comment by pporrasebi** [comment]
Regarding the 'part_of' relationship, I would like to clarify if it can be used to represent terms as being part of the ontology (some sort of self-reference). It seems in our case that we mainly use the relationship to put in the different terms just under the 'molecular interactions' root and then in several sub-branches where the relationship is the same: terms that are part of a category. The definition of BFO:0000050 seems generic enough, but I wanted to check jsut in case. 

We had a look at the remaining relationships and they do not seem to be used in the CV at all, they are probably default remnants from when the file was created, they will be eliminated. So I believe the only one we need to map is 'part_of' and that would do it.

**Comment by cthoyt** [comment]
@pporrasebi excellent, thanks for looking into this!

**Comment by pporrasebi** [comment]
No problem. Can you confirm we can use BTO:0000050 as explained above, please? Then I can apply the changes to the master branch.

**Comment by matentzn** [comment]
> Regarding the 'part_of' relationship, I would like to clarify if it can be used to represent terms as being part of the ontology

You mean like:

`TERM:001 part_of obo:MSIPSI`?

I would definitely _not_ do that. No one as far as I know would make that relationship explicit (if its _in_ the owl file, its part of it). 

part of (BFO:000050) should be used only as a mereological relation relating to classes (or individuals) in your ontology, if they can truly be considered part of each other.

>  we mainly use the relationship to put in the different terms just under the 'molecular interactions' root

So in this case, if a term is a part of the molecular interactions it is nested under its fine to use `BFO:0000050`, just be careful its really is a part-of relation, not a `kind-of` (`is-a`) relation!

> terms that are part of a category

This is a very `meta` way of phrasing it - there are only classes, not categories. A class is part of another class. I assume by term, you mean again, a class? If so, only use BFO:000052 if both the term and, as you say, the category, are actually domain concepts and they can be physically or conceptually considered part of each other. If it is: term belongs to category X, BFO:0000052 is not the right relation (there is no relation for that in OWL - you need to define categories a broad domain concepts).

**Comment by pporrasebi** [comment]
OK, I think we might be using the part_of relationship too liberally in some cases. I will take a careful look at the use cases we have and clean our CV up beofre attempting to map to BFO terms.

**Comment by pporrasebi** [comment]
I have examined the relaionships that were given in the obo file and determined that no true 'part_of' relationships were depicted in the CV, so all have been replaced with 'is_a' and no links to BFO are needed.
