### ISSUE TITLE
Memberane complementation issues

### ISSUE THREAD

**Issue by sandraorchard** [HUPO-PSI/psi-mi-CV#450]
MAMTH paper has raised a few issues
1, We need to create new parent "membrane two hybrid"  Protein complementation methods specifically developed to assay for interactions of membrane proteins with both cytosolic or membrane-bound partners. 

2, MYTH MI:1320 becomes a child of that

3. ubiquitin reconstruction MI:0112 should be a child of new term 'membrane two hybrid' - plant people run it in onion cells and we have plenty of that data.

4. New term MAMTH, child of new term 'ubiquitin reconstruction' Definition - A membrane bait protein is tagged with the C-terminal half of ubiquitin (Cub) and a chimeric transcription factor, and a cytosolic or membrane-bound prey is tagged with the N-terminal half of ubiquitin (Nub). Upon interaction of bait and prey, the split halves form pseudoubiquitin, which is recognized by cytosolic deubiquitinating enzymes, resulting in cleavage of the transcription factor and expression of a reporter gene.

**Comment by luanalicata** [comment]
Done
