### ISSUE TITLE
Question: ontology terms for binary interactions

### ISSUE THREAD

**Issue by AD-git1** [HUPO-PSI/psi-mi-CV#454]
My apologies if this is of topic, but this seemed a good place to ask my question. I am retrieving protein-protein interaction information and a lot of that data is annotated with PSI-MI terms e.g. in the BioGRID database.
Now, I am only interested in binary, direct interactions i.e., no interactions through complex as is sometimes detected by e.g. co-immunoprecipitation. I am looking for an extensive list of PSI-MI terms that represent experiments only detecting binary direct interactions. I was wondering whether someone could provide some guidelines? The only answer I could find on a similar question was this stackoverflow answer: https://bioinformatics.stackexchange.com/a/740/18621

**Comment by luanalicata** [comment]
Hi, 
yes, it is possible to filter for 'direct interactions'. 
One easy option is to download the interactions as PSI-MI TAB 2.7 and then filter the column 'interaction Type' for 'direct interaction (MI:0407)' if you want only Interaction between molecules that are in direct contact with each other, usually identified by biophysical methodology, for the IMEx interactions you can filter directly from IntAct advanced search page (https://www.ebi.ac.uk/intact/home#advanced-search).
or 
If you also want also other physical binary interaction you should include also the term 'physical association (MI:0915)'. 
In IMEx consortium this is the rules that we adopt:
Any interaction in which the participants form a single n-ary complex (identified with
techniques that can ascertain that only one complex is present, like x-ray
crystallography), or a binary complex which may involve more interactors than those
identified in the experiment should be described as ‘Physical Association’. Any
interaction with the Interaction Detection Method = ‘affinity chromatography’ or one of
their children (e.g. coimmunoprecipitation, pulldown, TAP) with one bait and only ONE
prey should be mapped to ‘Physical Association’ (unless the interaction occurs in vitro
and consists of only 2 highly purified proteins in which case they should be mapped to
‘direct interaction’ (see below).

for more see: https://raw.githubusercontent.com/intact-portal/intact-portal-documentation/master/assets/intact-curation-manual.pdf

**Comment by AD-git1** [comment]
Thank you so much for the information!
