### ISSUE TITLE
policy for direct interaction and colocalization

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#60]
Curation policy should be refined for the assigment of
this 2 interaction types:

\- for Colocalisation see request 1397882 second case
(in summary can we consider that mass spec experiment
on very narrow subcellular area are detecting complexes?)

\- for direct interaction we propose that only in vitro
interactions with both partner purified prior
interaction are direct interaction.  

Reported by: luisa_montecchi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
