### ISSUE TITLE
 mv to obsolete colocalization by fluorescent probes cloning

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#61]
With the addition of confocal microscopy to the other
imaging techniques isn't it enough to specify the type
of microscope on the method and the tags on the
features. If this curation policy is agreed
colocalization by fluorescent probes cloning is
slightly useless. (Intact won't use this term anymore)  

Reported by: luisa_montecchi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
