### ISSUE TITLE
experimental role: unknown

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#62]
Current roles include bait and prey, fluorescence
acceptor and donor, self, suppressed and suppressed
gene and neutral component. You could have however a
experimental condition like isothermal calorimetry in
which the experimental method does nto make it possible
to assign a specific role to the interactor. I do not
feel comfortable using neutral since this is explicitly
used to indicate that the interactors did not have any
experimental bais.
There are also cases where the authors have given a
list of interactors and method used however have not
assigned a specific experiental role to each interactor
e.g. PMID:16189514
Is it possible to have an experimental role unknown for
cases where role is difficult to assess? 

Reported by: jyotikhadake

**Comment by linuxjackto1** [comment]
thanks www.movied.org
