### ISSUE TITLE
feature detection: prediction

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#63]
Still need the 'inference' hierarchy of interaction
detection to be copy under the 'feature detection', as
discuss during meeting in Geneve:

1272762/1272851 addition of inferences and predict to
feature detection – also make child of prediction from
structure and prediction from experimental information
. Approved

(I don't find any trace if it in the traker)

Reported by: aceol

**Comment by linuxjackto1** [comment]
thanks www.movied.org
