### ISSUE TITLE
children of delivery method

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#64]
expression cloning
bacterial 
transformation
electroporation
microinjection
passive uptake
divalent cation  
transduction (phages)
conjugation (conjugative plasmids)
mammalian
transfection
calcium phosphate
liposome
transfection agents (PMID:11248053 and others) 
viral/bacterial transduction
protein delivery
electroporation
microinjection
viral protein fusions (e.g. TAT protein fusions)
cationic lipids

Reported by: jyotikhadake

**Comment by linuxjackto1** [comment]
thanks www.movied.org
