### ISSUE TITLE
Protein array and antibody array

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#65]
Proposition :

Protein Array
- Purified protein array
- Antibody array
-\- Sandwich immunoassay microarray
-\- single-antibody protein microarray

Protein Array: (grand-parent term)
A protein microarray consists of antibodies, 
proteins, protein fragments, peptides, aptamers or 
carbohydrate elements that are coated or immobilized 
in a grid-like pattern on small surfaces. The arrayed 
molecules are then used to screen and assess patterns 
of interaction with samples containing distinct 
proteins or classes of proteins.There are apparently 
two main kinds of protein array. Either the proteins 
are spotted on the array after being purified 
(purified protein array) or antibodies are spotted in 
order to catch the proteins from any cell lysate 
(antibody array).

'Purified Protein Array': (previous definition of 
protein Array)
The protein array technology allows the screening of 
biochemical activities or binding abilities of 
hundreds or thousands of protein samples in parallel. 
After synthesis and purification by high-throughput 
methodologies, the proteins are printed onto the chip 
by using an instrument (micro-arrayer) that is 
capable of spotting liquid samples in a reproducible 
manner onto a planar support. The ordered protein 
array can then be probed with labelled molecules to 
identify proteins that bind to the bait.

Antibody array:
Antibody microarrays fall into one of two subtypes: 
those using matched antibody pairs for sandwich-type 
assays and those utilizing single antibodies and a 
sample labeling methodology.

The sandwich immunoassay microarray:
The sandwich immunoassay microarray consists of 
arrayed capture antibodies and appropriate control 
and orientation elements. Assays are performed by 
adding an antigen standard or test sample, followed 
by a detector antibody . The detector antibody is 
either modified with a directly detectable label 
(enzyme, fluorescent molecule, isotope, etc.), or it 
is biotinylated for detection after subsequent 
probing with labeled streptavidin.

single-antibody protein microarray:
single-antibody protein microarray protocols involves 
labeled samples. As in sandwich antibody pair arrays, 
the array platform consists of arrayed antibody (or 
antibodies). In this assay format, however, the 
captured protein analytes are themselves labeled for 
direct detection, obviating use of a detector 
antibody. The method requires that protein samples be 
labeled beforehand (e.g., with fluorescent molecule, 
isotope, or biotin). The label enables detection of 
any proteins in the sample that interact with the 
microarrayed antibody and associated elements.

PMID: 12454649
PMID: 12547427
PMID: 12610559
PMID: 15732136
PMID: 14595810
PMID: 16396508
PMID: 15907865

Reported by: krobbe4

**Comment by linuxjackto1** [comment]
thanks www.movied.org
