### ISSUE TITLE
main CV types as root terms?

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#66]
Currently the main CV types (feature type, alias type,
interaction type etc..) are reported as 'part_of' the
root term Molecular interaction. 
We could also have each of these as root terms. I am
not sure if it would be of any advantage, a part for
the better representation of the fact these are treated
as independed CVs. Maybe for parsers, or ontology
visualistion code it is better to leave the unique root
term as it is.
Any opinion or advice is welcome,
Luisa

Reported by: luisa_montecchi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
