### ISSUE TITLE
hierarchy of interactor type peptide-protein

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#67]
The current hierarchy of interactor type is 
-biopolimer
--protein
---peptide

Lukasz suggest to swap parental child relationship as
every protein is potentially a very long peptide but
not every peptide is a protein.

The resulting hierarchy of interactor type would be.
-biopolimer
--peptide
---protein

I do agree with the motivation, I just wonder if
biologist user won't find it weird as they are use to
the current protein - petide relationship.

Any comment?

Reported by: luisa_montecchi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
