### ISSUE TITLE
Revision of inference definitions

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#68]
Inference (MI0362): evidence based on human assumption
%Inferred by author: Evidence based on paper’s author
interpretation of experimental results.
%Inferred by curator: Evidence based on curator’s
interpretation of experimental results.

Posted by Andrew Chatr-aryamontri (MINT)

Reported by: luisa_montecchi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
