### ISSUE TITLE
crossreference qualifier for data from DataBases

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#69]
Partially curated data is available from some fo the
databases. This data can be included using the higher
level terms. The data however cannot have a primary
pubmed reference as it contains interactions present in
the databse not a pubmed ID. The only reference that
can be given to this set of interactions is database
publication reference, where the database and its
interaction data is described. A cross-reference
qualifier to describe such a cross-reference to
databases will be useful. Possible terms are
'source-reference' or 'database-reference'

Reported by: jyotikhadake

**Comment by linuxjackto1** [comment]
thanks www.movied.org
