### ISSUE TITLE
untraceable method  as Cv interaction detection method

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#70]
Unspecified method to temporaly annotate big dataset
imported within a database prior manual curation.
Should be a direct child of interaction detection
method so that it could potentially include
experimental method, predictions or inferences.

name : untraceable method
def : Unassigned method associated to interaction data
imported from a third party database, with potentially
different standards of curation.
is_a interaction detection method 

Reported by: luisa_montecchi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
