### ISSUE TITLE
\'unspecified\' and \'additional\' as EXPERIMENTAL  role 

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#71]
2 new experimental ROLES are proposed

unspecified : Should be use only when author do not
provide the information in the paper or supplementary
material about role even if the interaction method
generally requires roles.

additional ('the third guy') : Molecule required to
observe a binary interaction. This molecule may act as
stabilizer of any of the interaction partner or may be
a bridge molecules among them but the method do not
provide such resolution or evidence. (Mudpit, tri
hybrid etc..)

future role combinations when those terms will be in place 
- unspecified participant can only interact with other
unspecified
- additional can interact with bait prey or even self

Reported by: luisa_montecchi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
