### ISSUE TITLE
addition of \'sequence database\' term in CV database

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#72]
Currently CV database high level terms allow follow the
structure of the PSI main elements (interaction,
experiment, participant, feature, source). Within
participant xref we there are number of databases able
to describe whatever interactor type including small
molecules. 
%participant database xref   MI:0473 
%cabri   MI:0246 
%chebi   MI:0474 
%cygd    MI:0464 
%ddbj/embl/genbank   MI:0475 
%ensembl     MI:0476 
%entrez gene/locuslink   MI:0477 
%flybase     MI:0478 
%huge    MI:0249 
%international protein index     MI:0675 
%kegg    MI:0470 
%mgd/mgi     MI:0479 
%newt    MI:0247 
%omim    MI:0480 
%refseq      MI:0481 
%resid   MI:0248 
%rfam    MI:0482 
%rgd     MI:0483 
%sequence ontology   MI:0601 
%sgd     MI:0484 
%uniparc     MI:0485 
%uniprot knowledge base      MI:0486 
%wormbase    MI:0487 

Sequence database would be a child of participant db
xref and have as children all appropriate dbs :

%participant database xref   MI:0473 
%cabri   MI:0246 
%chebi   MI:0474
%newt    MI:0247 
%resid   MI:0248
%sequence ontology   MI:0601
new Sequence database xref  
%cygd    MI:0464 
%ddbj/embl/genbank   MI:0475 
%ensembl     MI:0476 
%entrez gene/locuslink   MI:0477 
%flybase     MI:0478 
%huge    MI:0249 
%international protein index     MI:0675 
%kegg    MI:0470 
%mgd/mgi     MI:0479  
%omim    MI:0480 
%refseq      MI:0481  
%rfam    MI:0482 
%rgd     MI:0483  
%sgd     MI:0484 
%uniparc     MI:0485 
%uniprot knowledge base      MI:0486 
%wormbase    MI:0487 

The main advantage would be an easier checking of that
a  sequence is provided for each participant within a
PSI file (minimal requirment)

Reported by: luisa_montecchi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
