### ISSUE TITLE
Obsolete milli/micro/nano units in CV paramenter unit

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#73]
These terms are redundant with the attribute exponent
of any parameter instance. Moreover the combination of
units that implicitly refer to exponent with the
exponent attribute could be very messy. 
The paramenter CV should have only main units like
(molar,second) and no derived children.

Reported by: luisa_montecchi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
