### ISSUE TITLE
small molecule - role= cofactor

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#74]
Probably a Biological rather than experimental role.

Also need to consider the role played by small
molecules which change during a reaction e.g. ATP
during a kinase reaction donating a phosphate. Not
really a neutral component under those circumstances -
have BioPax appropriate terms we can use.

Sandra

Reported by: orchard

**Comment by linuxjackto1** [comment]
thanks www.movied.org
