### ISSUE TITLE
Update of methods to become less protein-centric

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#75]
Many of the methods could become more generic just by a
slight rewriting of the description to encompass
nucleic acids and also small molecules. The example I
came across was "filter binding" - from the description
I couldn't use it to describe a protein-nucleic acid
interaction but in fact there  was no change to the
technique. Similarly, I used filter binding methods for
many years to separate radiolabelled proteins from
32P-ATP which could be used to demonstrate a
protein:small molecule interaction. We need to go
through all the methods to highlight those which could
be made more generic and create new children if necessary.

Sandra

Reported by: orchard

**Comment by linuxjackto1** [comment]
thanks www.movied.org
