### ISSUE TITLE
Nucleic acid - synthetic

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#77]
Many papers use short synthetic NAs as substrates or
for crystallisation purposes. Their sequences are
largely irrelevant and sometimes not given. I was
wondering if we should consider entering some generic
terms which will eliminate the need for either sequence
or xref, but would allow curators to indicate the
presence of NA without firther detail .PolyA and Poly
AT/AU would be obvious examples but we may need
something even more generic than that for polymerase
reactions.

Sandra

Reported by: orchard

**Comment by linuxjackto1** [comment]
thanks www.movied.org
