### ISSUE TITLE
Polymerase

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#78]
Polymerase as a general enzyme type (with at least 4
children DNA-dependent RNA, RNA-dependent RNA,
DNA-dependent DNA, RNA-dependent DNA) -  this then
leads to a  new Interaction Type being need
"elongation" or something similar, which could be
generic enoough to also cover protein synthesis should
we ever need to.

Sandra

Reported by: orchard

**Comment by linuxjackto1** [comment]
thanks www.movied.org
