### ISSUE TITLE
Tag vs Tagged: consistency request

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#79]
Can we please bring consistency to the 'feature type'
branch ?  Some of the terms used are nouns ('binding
site', 'mutation') and some of then adjectives ('flag
tagged', 'isotope labelled').

My take on it is the branch starts as 'feature type'
and thus the terms underneath should specify/reflect 
the type of the _feature_ (ie 'isotope tag', 
'gst tag' etc) not what was doen to the protein in
question (ie that 'it was labelled', 'it was tagged',
etc) 

also, 's' should be dropped from 'fusion proteins' ;o)

Reported by: lukasz99

**Comment by linuxjackto1** [comment]
thanks www.movied.org
