### ISSUE TITLE
yeast two hybrid-specific features

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#80]
there's currently no way to specify the domains used
to prepare fusions used in yeast two hybrid experiments.
the minimum set seems to be: 

\- DNA-binding domain fusion
- activation domain fusion

terms, both added as children of 'fusion protein(s)'
with specific domain types further added as children of
these two

Reported by: lukasz99

**Comment by linuxjackto1** [comment]
thanks www.movied.org
