### ISSUE TITLE
from Andrew tag antibody addition to participant detection

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#81]
1-In Participant identification method
Children of western blot are Monoclonal and polyclonal
antibody. I suggest to add anti-tag antibody

2-In Participant identification method
Immunostaining doesn’t allow to specify what kind of 
antibody has been used. I suggest to add in the
ontology monoclonal, polyclonal and anti-tag antibody 

Reported by: luisa_montecchi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
