### ISSUE TITLE
from Andrew : new two hybrid methods depending on the fusion

### ISSUE THREAD

**Issue by noedelta** [HUPO-PSI/psi-mi-CV#82]
1-Gal4 transcription regeneration
Stan Fields powerful genetic selections Chien CT,
Bartel PL, Sternglanz R, Fields S   The two-hybrid
system: a method to identify and clone genes for
proteins that interact with a protein of interest   Proc
Natl Acad Sci U S A. 1991 Nov 1;88(21):9578-82    1946372

2-Gal4 transcription regeneration
Marc Vidal  genetic markers are reversed; selection
against an interaction is possible  Vidal M, Brachmann
RK, Fattaey A, Harlow E, Boeke JD   Reverse two-hybrid
and one-hybrid systems to detect dissociation of
protein-protein and DNA-protein interactions.   Proc Natl
Acad Sci U S A. 1996 Sep 17;93(19):10315-20   8816797

3-LexA/B52 transcription regeneration
Roger Brent LexA DB eplaces Gal4 DB; B52 acidic seq
replaces GAL4 AD    Zhong J, Zhang H, Stanyon CA, Tromp G,
Finley RL Jr    A strategy for constructing large protein
interaction maps using the yeast two-hybrid system:
regulated expression arrays and two-phase mating.
Genome Res 2003, 13:2691-2699   14613974

4-mammalian two-hybrid
Eric Fearon Gal4 BD; VP16 AD; luciferase reporter
Fearon ER, Finkel T, Gillison ML, Kennedy SP, Casella
JF, Tomaselli GF, Morrow JS, Van Dang C.    Karyoplasmic
interaction selection strategy: A general strategy to
detect protein-protein interactions in mammalian cells
Proc Natl Acad Sci U S A. 1992 Sep 1;89(17):7958-62   1387709

5-bacterial two-hybrid
Daniel Ladant   cAMP signaling pathway reconstitution;
genetic selection   Karimova G, Pidoux J, Ullmann A,
Ladant D    A bacterial two-hybrid system based on a
reconstituted signal transduction pathway   Proc Natl
Acad Sci U S A. 1998 May 12;95(10):5752-6.    9576956

6- split ubiquitin
Wolf Frommer    reconstitution of N-ter Nub & C-ter Cub
ubiquitin halves releases LexA-VP16 transcription
factor  Obrdlik P, El-Bakkoury M, Hamacher T, Cappellaro
C, Vilarino C, Fleischer C, Ellerbrok H, Kamuzinzi R,
Ledent V, Blaudez D, Sanders D, Revuelta JL, Boles E,
Andre B, Frommer WB.    K+ channel interactions detected
by a genetic system optimized for systematic studies of
membrane protein interactions   Proc Natl Acad Sci U S A.
2004 Aug 17;101(33):12242-7   15299147

6- LUMIER luminescence-based mammalian interactome mapping
Jeff Wrana  pulldown NOT genetic interaction strategy,
therefore not really two-hybrid Barrios-Rodiles M,
Brown KR, Ozdamar B, Bose R, Liu Z, Donovan RS, Shinjo
F, Liu Y, Dembowy J, Taylor IW, Luga V, Przulj N,
Robinson M, Suzuki H, Hayashizaki Y, Jurisica I,
Wrana JL    High-throughput mapping of a dynamic signaling
network in mammalian cells  Science. 2005 Mar
11;307(5715):1621-5   15761153

7-MAPPIT mammalian protein-protein interaction trap

Reported by: luisa_montecchi

**Comment by linuxjackto1** [comment]
thanks www.movied.org
